//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegoShoePH.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NegoShoePH.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[ItemBrand](
        ///	[RecordID] [int] IDENTITY(1,1) NOT NULL,
        ///	[Brand] [nvarchar](150) NOT NULL,
        /// CONSTRAINT [PK_Brand] PRIMARY KEY CLUSTERED 
        ///(
        ///	[RecordID] ASC
        ///)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///) ON [PRIMARY].
        /// </summary>
        public static string CREATE_ITEMBRAND_TABLE {
            get {
                return ResourceManager.GetString("CREATE_ITEMBRAND_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Items](
        ///	[RecordID] [int] IDENTITY(1,1) NOT NULL,
        ///	[ItemName] [nvarchar](150) NOT NULL,
        ///	[Brand] [int] NOT NULL,
        ///	[ProductType] [int] NOT NULL,
        ///	[Description] [nvarchar](max) NULL,
        ///	[TotalQuantity] [int] NOT NULL,
        ///	[OfficeQuantity] [int] NOT NULL,
        ///	[HouseQuantity] [int] NOT NULL,
        ///	[Filename] [nvarchar](50) NULL,
        ///	[ImageBase64] [nvarchar](max) NULL,
        ///	[Remarks] [nvarchar](500) NULL,
        /// CONSTRAINT [PK_Items] PRIMARY KEY CLUSTERED 
        ///(
        ///	[RecordID] ASC
        ///)WITH (PAD_INDEX = OFF, STATI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CREATE_ITEMS_TABLE {
            get {
                return ResourceManager.GetString("CREATE_ITEMS_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[ItemType](
        ///	[RecordID] [int] IDENTITY(1,1) NOT NULL,
        ///	[ProductType] [nvarchar](100) NOT NULL,
        /// CONSTRAINT [PK_ProductType] PRIMARY KEY CLUSTERED 
        ///(
        ///	[RecordID] ASC
        ///)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///) ON [PRIMARY].
        /// </summary>
        public static string CREATE_ITEMTYPE_TABLE {
            get {
                return ResourceManager.GetString("CREATE_ITEMTYPE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE TABLE [dbo].[TEMPTBL](
        ///	[test] [nchar](10) NULL,
        ///	[RecordID] [int] NOT NULL,
        /// CONSTRAINT [PK_TEMPTBL] PRIMARY KEY CLUSTERED 
        ///(
        ///	[RecordID] ASC
        ///)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///) ON [PRIMARY].
        /// </summary>
        public static string CREATE_TEMP_TABLE {
            get {
                return ResourceManager.GetString("CREATE_TEMP_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[ItemBrand] ON;
        ///INSERT [dbo].[ItemBrand] ([RecordID], [Brand]) VALUES (1, N&apos;Jordan&apos;);
        ///INSERT [dbo].[ItemBrand] ([RecordID], [Brand]) VALUES (2, N&apos;Mitchell &amp; Ness&apos;);
        ///INSERT [dbo].[ItemBrand] ([RecordID], [Brand]) VALUES (3, N&apos;Nike&apos;);
        ///INSERT [dbo].[ItemBrand] ([RecordID], [Brand]) VALUES (4, N&apos;New Era&apos;);
        ///INSERT [dbo].[ItemBrand] ([RecordID], [Brand]) VALUES (5, N&apos;Field Grade&apos;);
        ///INSERT [dbo].[ItemBrand] ([RecordID], [Brand]) VALUES (6, N&apos;Adidas&apos;);
        ///SET IDENTITY_INSERT [dbo].[Ite [rest of string was truncated]&quot;;.
        /// </summary>
        public static string INSERT_ITEMBRAND_DATA {
            get {
                return ResourceManager.GetString("INSERT_ITEMBRAND_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET IDENTITY_INSERT [dbo].[ItemType] ON ;
        ///INSERT [dbo].[ItemType] ([RecordID], [ProductType]) VALUES (1, N&apos;Cap&apos;);
        ///INSERT [dbo].[ItemType] ([RecordID], [ProductType]) VALUES (2, N&apos;Shoe&apos;);
        ///INSERT [dbo].[ItemType] ([RecordID], [ProductType]) VALUES (3, N&apos;Shirt&apos;);
        ///INSERT [dbo].[ItemType] ([RecordID], [ProductType]) VALUES (4, N&apos;Short&apos;);
        ///INSERT [dbo].[ItemType] ([RecordID], [ProductType]) VALUES (5, N&apos;Slides/Hydro&apos;);
        ///SET IDENTITY_INSERT [dbo].[ItemType] OFF;.
        /// </summary>
        public static string INSERT_ITEMTYPE_DATA {
            get {
                return ResourceManager.GetString("INSERT_ITEMTYPE_DATA", resourceCulture);
            }
        }
    }
}
